# Generated by Django 4.2.28 on 2026-02-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('proto_data', models.TextField(blank=True)),
                ('conference', models.CharField(blank=True, db_index=True, max_length=150)),
                ('team_type', models.CharField(blank=True, choices=[('Club', 'Club'), ('Varsity', 'Varsity')], db_index=True, max_length=20)),
                ('roster_male', models.PositiveIntegerField(blank=True, null=True)),
                ('roster_female', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_current', models.DateField(blank=True, null=True)),
                ('mascot', models.CharField(blank=True, max_length=255)),
                ('school_website', models.URLField(blank=True)),
                ('athletic_dept_website', models.URLField(blank=True)),
                ('cycling_website', models.URLField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('address_complete', models.CharField(blank=True, max_length=255)),
                ('geocode_raw', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='school-logos/')),
                ('road', models.BooleanField(default=False)),
                ('mtb_xc', models.BooleanField(default=False)),
                ('mtb_st', models.BooleanField(default=False)),
                ('mtb_enduro', models.BooleanField(default=False)),
                ('mtb_downhill', models.BooleanField(default=False)),
                ('mtb_slalom', models.BooleanField(default=False)),
                ('cyclocross', models.BooleanField(default=False)),
                ('head_coach', models.CharField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('program_strengths', models.TextField(blank=True)),
                ('avg_cost', models.CharField(blank=True, max_length=100)),
                ('enrollment', models.CharField(blank=True, max_length=100)),
                ('acceptance_rate', models.CharField(blank=True, max_length=100)),
                ('graduation_rate', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'school')},
            },
        ),
    ]
