# Generated by Django 4.2.28 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='geocode_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('geocoded', 'Geocoded'), ('review', 'Needs Review'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='geocode_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
