# Generated by Django 4.2.28 on 2026-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_geocode_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nces_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='nces_schoolyear',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='nces_unitid',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
