# Generated by Django 4.2.28 on 2026-02-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_nces_name_school_nces_schoolyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cycling_program_status',
            field=models.CharField(choices=[('active', 'Active'), ('limited', 'Limited'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], db_index=True, default='active', max_length=20),
        ),
    ]
