# Generated by Django 4.2.28 on 2026-02-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_conference_long_name_conference_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='institution_control',
            field=models.CharField(choices=[('public', 'Public'), ('private_nonprofit', 'Private Nonprofit'), ('private_for_profit', 'Private For-Profit'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='institution_level',
            field=models.CharField(choices=[('four_year', 'Four-Year'), ('two_year', 'Two-Year'), ('less_than_two_year', 'Less Than Two-Year'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='locale',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
