# Generated by Django 4.2.28 on 2026-02-23 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0007_school_institution_control_school_institution_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(default='schools.School', max_length=100)),
                ('mapping_json', models.JSONField(default=dict)),
                ('unique_key_fields', models.JSONField(default=list)),
                ('required_fields', models.JSONField(default=list)),
                ('defaults_json', models.JSONField(default=dict)),
                ('type_rules', models.JSONField(default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DataLoadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='data-loads/input/')),
                ('dry_run', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('report_file', models.FileField(blank=True, upload_to='data-loads/reports/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='schools.importschema')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_load_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
