# Generated by Django 4.2.28 on 2026-02-25

from django.db import migrations, models
from django.db.models import Q


def hide_non_eastern_schools(apps, schema_editor):
    School = apps.get_model('schools', 'School')

    # Default all schools to hidden, then unhide schools tied to Eastern conference records.
    School.objects.all().update(hidden=True)
    School.objects.filter(
        Q(conference__name__iexact='Eastern')
        | Q(conference__name__icontains='Eastern')
        | Q(conference__acronym__iexact='ECCC')
    ).update(hidden=False)


def unhide_all_schools(apps, schema_editor):
    School = apps.get_model('schools', 'School')
    School.objects.all().update(hidden=False)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('schools', '0009_school_track_and_seed_colorado_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(hide_non_eastern_schools, reverse_code=unhide_all_schools),
    ]
