# Generated by Django 4.2.28 on 2026-02-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CMSNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(db_index=True, max_length=220, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('wide', 'Wide')], default='standard', max_length=20)),
                ('show_title', models.BooleanField(default=True)),
                ('show_sidebar_navigation', models.BooleanField(default=True)),
                ('nav_order', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms.cmsnavigation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.cmspage')),
            ],
            options={
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CMSWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.JSONField(default=list)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CMSWidgetPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_path', models.CharField(blank=True, help_text='Use values like / for homepage or /about', max_length=255)),
                ('slot', models.CharField(choices=[('content_top', 'Content Top'), ('content_bottom', 'Content Bottom'), ('sidebar', 'Sidebar'), ('home', 'Home')], default='content_bottom', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_placements', to='cms.cmspage')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='cms.cmswidget')),
            ],
            options={
                'ordering': ['slot', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('external_url', models.URLField(blank=True)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.cmsnavigation')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='cms.cmspage')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.cmsnavitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
