# Generated by Django 4.2.28 on 2026-02-25 17:48

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('invitee_name', models.CharField(blank=True, max_length=255)),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_access_code_expiry)),
                ('bound_device_id', models.CharField(blank=True, max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_code', models.CharField(blank=True, max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('cookie', 'Cookie check')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('not_found', 'Not found'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('device_mismatch', 'Device mismatch'), ('invalid_input', 'Invalid input')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='accounts.accesscode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
