# Generated by Django 4.2.28 on 2026-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_discipline_visibility_and_school_mtb'),
        ('accounts', '0003_accesscode_accesscodelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_conferences',
            field=models.ManyToManyField(blank=True, help_text='Conferences this staff user can manage in Django Admin.', related_name='conference_admin_users', to='schools.conference'),
        ),
    ]
